config/routes.rb
Rails.application.routes.draw do

  resources :groups do
  	resources :posts
  end

  root :to => "groups#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/activerecord_example.rb
require  'active_record'
class Activerecord_example

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :physician
  belongs_to :patient
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :pictures, as: :imageable
  has_many :subordinates, class_name: "Employee",
                          foreign_key: "manager_id"
  belongs_to :manager, class_name: "Employee"
end

app/models/group.rb
class Group < ActiveRecord::Base

  serialize :description
  has_many :posts
  validates :title, :presence => true
end

app/models/instancedemo.rb
class Instancedemo
  def initialize
    @v =1
  end
end

Instancedemo.class_eval do
  def test
    p @v
    p "test"
  end
end
obj = Instancedemo.new
obj.instance_eval do
  self
  @v = 2
  puts @v
end
obj.test

app/models/logger.rb
require 'logger'

module Logging
  attr_accessor :logger

  def logger
    return @logger if @logger # allow items to have own loggers
    @@logger ||= Logger.new(STDERR)
    puts "Instance Class REF ID#{@@logger.__id__}"
    puts "Class ID #{self.class.logger.__id__}"
    @@logger
  end

  module ClassMethods
    def logger= logger
      @logger = logger
    end

    def logger
      @logger ||= Logger.new(STDERR)
      puts "Class Instance REF ID #{@logger.__id__}"
      @logger
    end
  end

  def self.included(base)
    base.extend(ClassMethods)
  end
end

class Test

  include Logging

  def wow
    logger.info 'wow'
  end
end

t = Test.new

# should be the same
puts "Loggers are #{t.logger.__id__ == Test.logger.__id__ ? '' : 'not '}the same"

Test.logger = Logger.new('/dev/null')

# should still be the same
puts "Loggers are #{t.logger.__id__ == Test.logger.__id__ ? '' : 'not '}the same"

lg = Test.logger.__id__
t.logger =  Logger.new(STDERR)

# class logger should be same
puts "Class Logger is #{Test.logger.__id__ == lg ? 'still the' : 'not'} same"

# class and instance logger should be different
puts "Loggers are #{t.logger.__id__ == Test.logger.__id__ ? '' : 'not '}the same"

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, :through => :appointments
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments
  has_many :patients, :through => :appointments
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :group
  validates :content, :presence => true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :pictures, as: :imageable
end

app/models/test.rb
# module ActAsActivable
#   def self.included(base)
#     base.send(:include, InstanceMethods)
#     base.extend ClassMethods
#     base.class_eval do
#       def  testclass
#         p self
#         p "i am #{base}"
#       end
#     end
#     # p base
#   end
#
#   def testself
#     p self
#   end
#   module InstanceMethods
#     def active?
#       is_active
#     end
#   end
#
#   module ClassMethods
#     def all_active(reload = false)
#       @all_active = nil if reload
#       @all_active ||= active.all
#     end
#   end
# end
#
# class Test
#   include ActAsActivable
# end
#
# test = Test.new
# p test.testself
# p
# p Test.methods
#
# p '..........'
# p test.methods




# module ActAsActivable
#   extend ActiveSupport::Concern
#
#   included do |base|
#     scope :active, -> {where(is_active: true)}
#   end
#
#   module ClassMethods
#     def all_active(reload = false)
#       @all_active = nil if reload
#       @all_active ||= active.all
#     end
#   end
#
#   # instance methods
#   def active?
#     is_active
#   end
# end
#
# class Test
#   include ActAsActivable
# end
#
# test = Test.new
# p Test.methods
#
# p '..........'
# p test.methods




# class Myclass
#   def greet
#     puts "hello!"
#   end
#
#   def greet_with_log
#     puts "Calling method..."
#     greet_without_log
#     puts "... Method called"
#   end
#
#   alias_method :greet_without_log, :greet
#   alias_method :greet, :greet_with_log
# end
#
# myclass = Myclass.new
# myclass.greet


require 'active_record'
ActiveRecord::Base

class Myclass
  def save; end
  def save!; end
  def new_record?; true; end

  include ActiveRecord::Validations
  attr_accessor :attr
  validates_length_of :attr, :minimum => 4
end

obj= Myclass.new
p obj.new_record?

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	
  def index
		@groups = Group.all
	end

  def show
    @group = Group.find(params[:id])
    @posts = @group.posts
  end

  def new

    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = 'Post was successfully created.'
      redirect_to group_path(@group), alert: '创建成功'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])    
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
        redirect_to group_path(@group)
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    if @group.destroy
      redirect_to groups_path
    end
  end

  private
    
    def group_params
      params.require(:group).permit(:title, :description)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_group
  def new
    @post = @group.posts.build
  end

  def create
    @post = @group.posts.new(post_params)
    if @post.save
      redirect_to group_path(post_params)
    else
      render :new
    end
  end

  def edit
    @post = @group.posts.find(params[:id])
  end

  def update
    @post = @group.posts.find(params[:id])

    if @post.update(post_params)
    redirect_to group_path(@group)
    else
    render :edit
    end
  end

  def destroy
    @post = @group.posts.find(params[:id])
    @post.destroy
    redirect_to group_path(@group)
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def find_group
    @gruop = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<div class="span12">
  <%= simple_form_for @group do |f| %>
      <%= f.input :title, :input_html => {:class => "input_xxlarge"} %>
      <%= f.input :description, :input_html => {:class => "input_xxlarge"} %>
      <div class="form_actions">
        <%= f.submit "Submit", :disable_with => "Submiting...", :input_html => {:class => "btn btn_primary"} %>
      </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="span12">
  <div class="group">
    <%= link_to("New group", new_group_path , :class => "btn btn-mini btn-primary pull-right") %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <td>#</td>
        <td>Titile</td>
        <td>Description</td>
      </tr>
    </thead>

    <tbody>
      <% @groups.each do |group| %>
      <tr>
        <td>#</td>
        <td><%= link_to("group.title", group_path(group)) %></td>
        <td><%= group.description %></td>
        <td><%= link_to("Edit", edit_group_path(group) , :class => "btn btn-mini") %>
            <%= link_to("Delete", group_path(group), :class => "btn btn-mini" , :method => :delete, :confirm => "Are you sure?") %>
        </td>
      </tr>p
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="span12">
  <%= simple_form_for @group do |f| %>
      <%= f.input  :title, :input_html => {:class => "input-xxlarge"}%>
      <%= f.input :description, :input_html => {:class => "input-xxlarge"} %>
      <div class="form-actions">
        <%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="span12">
  <div class="group">
    <%= link_to("Edit", edit_group_path(@group) , :class => "btn btn-mini btn-primary pull-right") %>
  </div>
  <h2><%= @group.title %></h2>
  <p><%= @group.description %></p>

  <table class="table">
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.content %></td>
          <td><%= link_to("Edit", edit_group_post_path(post.group, post) , :class => "btn btn-mini") %>
              <%= link_to("Delete", group_post_path(post.group, post) , :class => "btn btn-mini", :method => :delete, :confirm => "Are you sure?") %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/posts/edit.html.erb
<div class="span12">
  <%= simple_form_for [@group,@post] do |f| %>
      <%= f.input :content, :input_html => {:class => "input-xxlarge"} %>

      <div class="form-actions">
        <%=f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary"%> 
      </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="span12">
  <%= simple_form_for [@group, @post] do |f| %>
      <%= f.input :content, :input_html => { :class => "input-xxlarge"} %>
        <div class="form-actions">
              <%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary" %>
        </div>
  <% end %>
</div>